### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by azebolsky** [azebolsky/Park-Texas#3]
Hey Daniel,  I am struggling to find the best way to connect my profile page the way I want which is where they can click on view my profile and if they have not set anything up, they will just see "no profile information has been setup, please fill out below information."  Would it be possible to add in google information if they do not have a profile set up which would say "welcome (name) at (email)"?

I have journal entries I would like to add as well which I may set up from their profile with a dropdown of all parks to show what the journal is attached to.  Also, I don't think I want to have the availability of users to create a park so I may try to just add in all parks in Texas so they can simply choose from a long dropdown of the parks.

I need to discuss the above topics to get a feel of how everything will go.

Thanks!

P.S. how are issue tickets in "the real world" written?  Are they more brief than this? more specific?  I'm assuming they wouldn't be discussing planning of projects but more specific bugs.

**Comment by myDeveloperJourney** [comment]
During this meeting, we discovered some potential issues with connecting the models and also making sure we were consistent in having all the properties from the ERD incorporated in the Schemas
